language: android
android:
  components:
    - android-22
    - build-tools-22.0.0
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew build
notifications:
  hipchat:
    rooms:
      secure: pofqFB1dvZq/Ue0okcuy3cWDKMxkq/5acPGoK2VlB8Sj1OEPm3Uau2y4Kx0DKtV9vQCLmAwc9Wvy26eIbihFIjzM6O8BDS5kdWlApJIlnJtT5hJ/YT5JB0jDHW6P1aU4muu9PXtBMMZhUWmBU3jIUPTgiLbCAygCYPGOkVRku+g=
